# Общая конфигурация приложения

# Свойства сервера
server:
  port: 8080

# Конфигурация spring
spring:
  datasource: # соединение с БД
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:15433/nexing
    username: nexing
    password: nexing
    hikari: # конфигурация пула соединения с БД
      initialization-fail-fast: true
      auto-commit: false
      maximum-pool-size: 6
      idle-timeout: 60000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      pool-name: springHikariCP
      data-source-properties:
        stringtype: unspecified
  jpa: # настройка JPA
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
  jackson: # настройка сериализациии и десериализации jackson
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    serialization.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    serialization.WRITE_ENUMS_USING_TO_STRING: true
    deserialization.READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  liquibase: # конфигурация liquibase
    change-log: classpath:liquibase/changelog.xml
    enabled: true

# Конфигурация обработки задач
task:
  processing-cron: "0 */1 * * * *"
  max-thread-to-processing: 5 # максимальное значение воркеров
  limit: 10 # ограничение на выборку из бд данных

# Настройка Kafka
kafka:
  common:
    topic: tasks
    group-id: task-group
  reply:
    topic: task-result
    correlation-header-name: task-id
    group-id: task-result-group
  bootstrap-servers: localhost:9092

# Настройка уровня логирования
logging:
  level:
    liquibase: INFO

# Настройка actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
