version: "3.9"
services:

  postgres:
    container_name: db-postgres
    image: postgres:15
    ports:
      - "15433:5432"
    volumes:
      - "./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=nexing
      - POSTGRES_PASSWORD=nexing
      - POSTGRES_DB=nexing

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
